#!/bin/sh

set -e

multiarch=arm-linux-gnueabihf
jdirname=java-7-openjdk-armhf
etcdir=/etc/java-7-openjdk

case "$1" in
purge)
    if [ -z "$jdirname" ] || [ -z "$etcdir" ]; then
	echo >&2 "$(basename $0): Internal error"
	exit 1
    fi
    # removals of config files in /etc is handled by dpkg

    # XXX should remove /etc/.java ???
    ;;
esac

# Automatically added by dh_makeshlibs
if [ "$1" = "remove" ]; then
	ldconfig
fi
# End automatically added section

