# -*- encoding: utf-8 -*-
# stub: rubyzip 1.1.6 ruby lib

Gem::Specification.new do |s|
  s.name = "rubyzip"
  s.version = "1.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Alexander Simonov"]
  s.date = "2015-06-17"
  s.email = ["alex@simonov.me"]
  s.files = ["README.md", "Rakefile", "TODO", "lib/zip.rb", "lib/zip/central_directory.rb", "lib/zip/compressor.rb", "lib/zip/constants.rb", "lib/zip/decompressor.rb", "lib/zip/deflater.rb", "lib/zip/dos_time.rb", "lib/zip/entry.rb", "lib/zip/entry_set.rb", "lib/zip/errors.rb", "lib/zip/extra_field.rb", "lib/zip/extra_field/generic.rb", "lib/zip/extra_field/old_unix.rb", "lib/zip/extra_field/universal_time.rb", "lib/zip/extra_field/unix.rb", "lib/zip/extra_field/zip64.rb", "lib/zip/extra_field/zip64_placeholder.rb", "lib/zip/file.rb", "lib/zip/filesystem.rb", "lib/zip/inflater.rb", "lib/zip/input_stream.rb", "lib/zip/ioextras.rb", "lib/zip/ioextras/abstract_input_stream.rb", "lib/zip/ioextras/abstract_output_stream.rb", "lib/zip/null_compressor.rb", "lib/zip/null_decompressor.rb", "lib/zip/null_input_stream.rb", "lib/zip/output_stream.rb", "lib/zip/pass_thru_compressor.rb", "lib/zip/pass_thru_decompressor.rb", "lib/zip/streamable_directory.rb", "lib/zip/streamable_stream.rb", "lib/zip/version.rb", "samples/example.rb", "samples/example_filesystem.rb", "samples/example_recursive.rb", "samples/gtkRubyzip.rb", "samples/qtzip.rb", "samples/write_simple.rb", "samples/zipfind.rb", "test/basic_zip_file_test.rb", "test/central_directory_entry_test.rb", "test/central_directory_test.rb", "test/data", "test/data/file1.txt", "test/data/file1.txt.deflatedData", "test/data/file2.txt", "test/data/globTest", "test/data/globTest.zip", "test/data/globTest/foo", "test/data/globTest/foo.txt", "test/data/globTest/foo/bar", "test/data/globTest/foo/bar/baz", "test/data/globTest/foo/bar/baz/foo.txt", "test/data/globTest/food.txt", "test/data/mimetype", "test/data/notzippedruby.rb", "test/data/rubycode.zip", "test/data/rubycode2.zip", "test/data/testDirectory.bin", "test/data/zip64-sample.zip", "test/data/zipWithDirs.zip", "test/deflater_test.rb", "test/entry_set_test.rb", "test/entry_test.rb", "test/errors_test.rb", "test/extra_field_test.rb", "test/file_extract_directory_test.rb", "test/file_extract_test.rb", "test/file_split_test.rb", "test/file_test.rb", "test/filesystem", "test/filesystem/dir_iterator_test.rb", "test/filesystem/directory_test.rb", "test/filesystem/file_mutating_test.rb", "test/filesystem/file_nonmutating_test.rb", "test/filesystem/file_stat_test.rb", "test/gentestfiles.rb", "test/inflater_test.rb", "test/input_stream_test.rb", "test/ioextras", "test/ioextras/abstract_input_stream_test.rb", "test/ioextras/abstract_output_stream_test.rb", "test/ioextras/fake_io_test.rb", "test/local_entry_test.rb", "test/output_stream_test.rb", "test/pass_thru_compressor_test.rb", "test/pass_thru_decompressor_test.rb", "test/settings_test.rb", "test/test_helper.rb", "test/unicode_file_names_and_comments_test.rb", "test/zip64_full_test.rb", "test/zip64_support_test.rb"]
  s.homepage = "http://github.com/rubyzip/rubyzip"
  s.licenses = ["BSD 2-Clause"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9.2")
  s.rubygems_version = "2.2.2"
  s.summary = "rubyzip is a ruby module for reading and writing zip files"
  s.test_files = ["test/zip64_full_test.rb", "test/deflater_test.rb", "test/inflater_test.rb", "test/filesystem", "test/filesystem/file_mutating_test.rb", "test/filesystem/dir_iterator_test.rb", "test/filesystem/directory_test.rb", "test/filesystem/file_nonmutating_test.rb", "test/filesystem/file_stat_test.rb", "test/output_stream_test.rb", "test/file_extract_directory_test.rb", "test/pass_thru_compressor_test.rb", "test/test_helper.rb", "test/ioextras", "test/ioextras/fake_io_test.rb", "test/ioextras/abstract_output_stream_test.rb", "test/ioextras/abstract_input_stream_test.rb", "test/basic_zip_file_test.rb", "test/input_stream_test.rb", "test/file_extract_test.rb", "test/pass_thru_decompressor_test.rb", "test/gentestfiles.rb", "test/file_test.rb", "test/local_entry_test.rb", "test/unicode_file_names_and_comments_test.rb", "test/central_directory_entry_test.rb", "test/entry_test.rb", "test/errors_test.rb", "test/data", "test/data/globTest", "test/data/globTest/foo", "test/data/globTest/foo/bar", "test/data/globTest/foo/bar/baz", "test/data/globTest/foo/bar/baz/foo.txt", "test/data/globTest/food.txt", "test/data/globTest/foo.txt", "test/data/rubycode2.zip", "test/data/zip64-sample.zip", "test/data/notzippedruby.rb", "test/data/file1.txt", "test/data/mimetype", "test/data/zipWithDirs.zip", "test/data/globTest.zip", "test/data/rubycode.zip", "test/data/testDirectory.bin", "test/data/file2.txt", "test/data/file1.txt.deflatedData", "test/entry_set_test.rb", "test/settings_test.rb", "test/zip64_support_test.rb", "test/file_split_test.rb", "test/central_directory_test.rb", "test/extra_field_test.rb"]
end
